# _config.yml
# For Ian's blog.
# Created  2014-01-04 Mostly copied from Rasmus Andersson.
# Modified 2014-02-07 Add base url

lsi: false
pygments: false
permalink: /:year/:month/:day/:title.html
baseurl: http://www.ianbarnes.me.uk
timezone: Europe/London

# Enable SmartyPants (curly quotes, long dashes, ellipses etc)

markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - footnotes

# rsms sets safe: false with this explanation: "Since GitHub pages overrides
# this to true, we test this value to see if we are running locally." OK... I
# wonder where he uses that?

safe: false


