title: Ian Barnes
author: Ian Barnes
description: Software developer

url: "https://www.ianbarnes.me.uk"

theme: minima
minima:
  date_format: "%Y-%m-%d %H:%M:%S %Z"
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  extensions: ["smart", "footnotes"]

rss: true
show_excerpts: true

timezone: Europe/Paris

# Navigation links in header
header_pages:
  - index.md
  - cv.md
  - projects.md
  - blog.md
  - contact.md

# Don't copy the Makefile across
exclude: [Makefile, README.md]
